### ISSUE TITLE
Star solution is drawing extra initial line

### ISSUE THREAD

**Issue by thomasdziedzic** [underscoreio/doodle#12]
Given the example solution code:

```
def star(sides: Int, skip: Int, radius: Double) = {
    val centerAngle = 360.degrees * skip / sides
    val elements = (0 to sides) map { index =>
        LineTo(Vec.polar(centerAngle * index, radius))
    }
    Path(elements) lineWidth 2
}
```

produces the following star for me:

![star with extra line](http://i.imgur.com/N8PfZu2.png)

with the following code piece: ```draw(star(10, 3, 100))```

**Comment by noelwelsh** [comment]
Thanks for reporting this. I've updated the example in Doodle and I'm updating the text in Creative Scala to fix this.
