### ISSUE TITLE
Initial running Fails with Java 8  / Windows 7

### ISSUE THREAD

**Issue by sylvesterjakubowski** [underscoreio/doodle#13]
P90Puma@P90PUMA-X58A ~/git/doodle (develop)
$ sbt.bat console
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; sup
port was removed in 8.0
[info] Loading project definition from C:\Users\P90Puma\git\doodle\project
Missing bintray credentials C:\Users\P90Puma\.bintray\.credentials. Some bintray
 features depend on this.
[info] Set current project to doodle (in build file:/C:/Users/P90Puma/git/doodle
/)
[error] Not a valid command: %*
[error] %*
[error]   ^

P90Puma@P90PUMA-X58A ~/git/doodle (develop)
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

P90Puma@P90PUMA-X58A ~/git/doodle (develop)
$ which java
/c/ProgramData/Oracle/Java/javapath/java

**Comment by sylvesterjakubowski** [comment]
My work around was installing SBT in windows 0.13.8 and I can run the doodle app using the installed sbt rather than the sbt.bat in the repo.

**Comment by noelwelsh** [comment]
Thanks for the report. It looks like you're running a Unix style shell under Windows---you have Unix style paths, prompt, etc. Is this the case? If so, you might find the the `sbt.sh` command works in your shell.

The error message about `%*` refers to a Windows shell scripting command.

**Comment by noelwelsh** [comment]
@sylvesterjakubowski can you comment on this? I'm going to close this issue if I don't hear back from you in a few days.

**Comment by sylvesterjakubowski** [comment]
I will try using the .sh command tonight to see if that helps out, I managed to work around this using the manually installed sbt, and I was using the git bash shell provided by github in windows.

**Comment by noelwelsh** [comment]
Assuming this is no longer a problem.
