### ISSUE TITLE
error: could not find implicit value for parameter canvas: doodle.backend.Canvas

### ISSUE THREAD

**Issue by xanderdunn** [underscoreio/doodle#17]
Because I've been unable to build doodle's master as a dependency in sbt (#16), I simply cloned the repo, `sbt publish-local`, and then I'm executing my code with `scala -classpath doodle_2.11.jar mycode.scala`

When mycode.scala looks like this: 
```scala
import doodle.core._
import doodle.syntax._
import doodle.jvm._
import doodle.examples._

object Test {
  def main(args: Array[String]) {
    Circle(10).draw
  }
}
```

I get the error `could not find implicit value for parameter interpreter: doodle.backend.Interpreter`.  I noticed that I can add this import at the top: 
```scala
import doodle.backend.StandardInterpreter._
```

and that no longer seems to be a problem.  Instead, I get `error: could not find implicit value for parameter canvas: doodle.backend.Canvas`.

Is `scala -classpath` not the right way to be referencing the library or are there additional import statements I need since the 0.1 release?  Or, perhaps I need to create a Canvas object and pass it to something?

**Comment by noelwelsh** [comment]
This is what you need

``` scala
import doodle.core._
import doodle.syntax._
import doodle.jvm.Java2DCanvas._
import doodle.backend.StandardInterpreter._
```

The crucial missing import is the `Java2DCanvas` one above.

**Comment by xanderdunn** [comment]
Ah, thanks a lot!
