### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by chaldar** [underscoreio/doodle#19]
I cloned the repo from github, ran 'sbt' followed by 'console'.  Things appeared all right.  But then:

    `scala> draw(Circle(10) fillColor Color.red)
    <console>:26: error: not found: value draw
           draw(Circle(10) fillColor Color.red)
           ^
    `
What am I doing wrong?  I am on Ubuntu 14.04 64-bit with OpenJDK 7.

**Comment by noelwelsh** [comment]
I've updated the README to have the correct syntax (which recently changed):

~~~scala
(Circle(10) fillColor Color.red).draw
~~~

Thanks for reporting this!
