### ISSUE TITLE
Path image coordinate system horizontally flipped?

### ISSUE THREAD

**Issue by indraastra** [underscoreio/doodle#24]
I'm not getting the following image when running the same snippet of code:

![screenshot from 2016-01-17 17 44 20](https://cloud.githubusercontent.com/assets/34575/12381590/fc91cf3e-bd41-11e5-9afd-73a21ccd0ca6.png)

Here's what I see:

![screenshot from 2016-01-17 17 47 11](https://cloud.githubusercontent.com/assets/34575/12381609/5b8a874c-bd42-11e5-8049-9c1dbe9fa7bb.png)

And when overlaid on a larger image (`(image on Rectangle(200, 200)).draw`):

![screenshot from 2016-01-17 17 48 10](https://cloud.githubusercontent.com/assets/34575/12381619/88695f90-bd42-11e5-84a7-85d07fde7b7f.png)

The only thing that draws as it should as per the example output is the decagon, which makes sense because it's symmetric. It might be related to issue #20.

**Comment by noelwelsh** [comment]
Thanks for the report, and sorry for the delay getting back to you (I've been travelling.) I'll take a look at this next week when I'll be working on Creative Scala, and I'll see if I can fix it then.

**Comment by noelwelsh** [comment]
Took a little bit longer than a week, but this is now fixed in the develop branch of Doodle.
