### ISSUE TITLE
fill color lives on as stroke color

### ISSUE THREAD

**Issue by tpolecat** [underscoreio/doodle#38]
Shared mutable state strikes again. The fill color for the wee circle reappears as the stroke color for the large circle. Maria from ScalaBridge just found this.

`circle(5).fillColor(Color.red) on circle(10) above circle(20)`

![image](https://cloud.githubusercontent.com/assets/1200131/23096572/2a325802-f5d4-11e6-8db0-18c72a326906.png)

I didn't look very closely but deleting [this line](https://github.com/underscoreio/doodle/blob/develop/jvm/src/main/scala/doodle/jvm/Java2D.scala#L107) fixes it.

Not submitting as a PR because I'm not convinced I understand what's going on.

**Comment by noelwelsh** [comment]
Thanks! I've fixed in latest release (0.7.0). Not sure what's going on either; presumably I don't understand the state within Java2D. It might be a bug in Java2D but either way this is the fix.
