### ISSUE TITLE
Add Scala 2.12 support

### ISSUE THREAD

**Issue by julienrf** [underscoreio/doodle#47]

**Comment by noelwelsh** [comment]
Closed in #51, and I've published 0.8.0 with 2.12 support. Big thanks to @SethTisue for the work behind this one!

**Comment by julienrf** [comment]
Are you sure the Scala.js artifacts are published? Sbt fails to resolve them and I don’t see them in the repository: https://dl.bintray.com/underscoreio/training/underscoreio/

**Comment by noelwelsh** [comment]
I think the problem here is assuming I have a clue about `sbt`. I'll take a look.

**Comment by julienrf** [comment]
Thanks!
