### ISSUE TITLE
Publish Doodle artefact

### ISSUE THREAD

**Issue by davegurnell** [underscoreio/doodle#7]
We should make the library part of Doodle available somewhere (possibly Bintray).

Doing so would require reorganising the codebase a little, splitting libraries from examples. Not sure what the implications are for JS either.

**Comment by julienrf** [comment]
+1 for this, I’d like to reuse it as a library (in Scala only)

**Comment by davegurnell** [comment]
I've published Doodle on Bintray and added instructions to the README.
